/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ItemController;
import Controller.OfertaController;
import Model.ItemModel;
import Model.OfertaModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hique
 */
public class OfertaGerarView extends javax.swing.JFrame {

    /**
     * Creates new form GerarOferta
     */
    public OfertaGerarView() {
        initComponents();
        init();
    }

    public void init() {
        DefaultTableModel tabela = (DefaultTableModel) TabelaItem.getModel();
        ItemController controlador = new ItemController();
        ArrayList<ItemModel> lista;
        lista = new ArrayList<>();
        lista = controlador.getItens();
        for (ItemModel i : lista) {
            Object[] dados = {i.getCod(), i.getOferta(), i.getPreco(), i.getEstoque()};
            tabela.addRow(dados);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaItem = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        codigoOferta1 = new javax.swing.JTextField();
        codigoOferta2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        desconto = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setTitle("Gerar ofertas");

        TabelaItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Valor", "Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaItem);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Gerar oferta com mais de um produto");

        codigoOferta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoOferta2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Digite o codigo dos itens");

        jButton3.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jButton3.setText("Gerar Oferta");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Digite quantos % de desconto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoOferta1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoOferta2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(jButton3)))
                    .addComponent(desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codigoOferta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(codigoOferta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codigoOferta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoOferta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoOferta2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String desc;
        String oferta1 = "", oferta2 = "", ofertaF;
        float preco1 = 0, preco2 = 0, precoF, descFloat;
        desc = desconto.getText().replace("%", "");
        if (codigoOferta2.getText().equals("") || codigoOferta1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Para gerar uma oferta, é preciso preencher os dois codigos");
            return;

        } else if (desc.matches("[0-9]+") == false || desc.equals("")) {
            JOptionPane.showMessageDialog(null, "Desconto invalido!");
            return;
        } else {
            int x = 0, co1, co2, co3, cod0, cod1;
            descFloat = Float.parseFloat(desc);
            if(descFloat > 100){
                JOptionPane.showMessageDialog(null, "Só é possível dar desconto de 0 até 100%");
                return;
            }
            co1 = Integer.parseInt(codigoOferta1.getText());
            co2 = Integer.parseInt(codigoOferta2.getText());

            OfertaController ofertaC = new OfertaController();
            ArrayList<OfertaModel> arrayO = new ArrayList<>();
            arrayO = ofertaC.getOferta();

            ItemController itemC = new ItemController();
            ArrayList<ItemModel> arrayC = new ArrayList();
            arrayC = itemC.getItens();

            for (int i = 0; i < arrayC.size(); i++) {
                if (arrayC.get(i).getCod() == co1) {
                    x++;
                    oferta1 = arrayC.get(i).getOferta().toString();
                    preco1 = arrayC.get(i).getPreco();
                    cod0 = arrayC.get(i).getCod();
                } else if (arrayC.get(i).getCod() == co2) {
                    x++;
                    oferta2 = arrayC.get(i).getOferta().toString();
                    preco2 = arrayC.get(i).getPreco();
                }
            }
            if (x == 2) {
                StringBuilder sb = new StringBuilder();
                sb.append(oferta1).append(" e ").append(oferta2);
                ofertaF = sb.toString();
                precoF = (preco1 + preco2) - ((preco1 + preco2) * (descFloat / 100));
                if (arrayO.isEmpty()) {
                    int newCodigo = 1;
                    OfertaModel o = new OfertaModel(ofertaF, newCodigo, precoF);
                    ofertaC.gerarOfertaDAO(o);
                    JOptionPane.showMessageDialog(null, "Desconto realizado com sucesso!");
                    return;
                } else {
                    int arraySize = arrayO.size() - 1, newCodigo;
                    newCodigo = arrayO.get(arraySize).getCod();
                    newCodigo = newCodigo + 2;
                    OfertaModel o = new OfertaModel(ofertaF, newCodigo, precoF);
                    ofertaC.gerarOfertaDAO(o);
                    JOptionPane.showMessageDialog(null, "Desconto realizado com sucesso!");
                    return;
                }

            }
        }
        JOptionPane.showMessageDialog(null, "Codigo invalido!");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OfertaGerarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OfertaGerarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OfertaGerarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OfertaGerarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OfertaGerarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaItem;
    private javax.swing.JTextField codigoOferta1;
    private javax.swing.JTextField codigoOferta2;
    private javax.swing.JTextField desconto;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
